package.json, src/extension.ts
Proposed fix for #11 
Add two new configuration options, *confPath* and *builtDocumentationPath*, to support controlling how documentation is resolved to html preview.
=> Remove reliance on hardcoded paths.

syntaxes/restructuredtext.tmLanguage
The field lists didn't match neither accent characters nor hyphens.
=> Add field lists support for special characters

syntaxes/restructuredtext.tmLanguage
This fixes highlighting of footnote links that contain a `-`.
=> Footnote links can contain `-`

src/features/rstLinter.ts
`${workspaceRoot}` in the `python.pythonPath` configuration is not expanded.
This leaves this error :
`Cannot {filename}. The executable was not found. Use the 'restructuredtext.linter.executablePath' setting to configure the location of the executable`.
This PR simply expands the configuration using `RstDocumentContentProvider.loadSetting`.
=> Expand macros in python.pythonPath configuration

.vscode/launch.json, .vscode/tasks.json, package.json, src/extension.ts, src/features/underline.ts, test/extension.test.ts, test/index.ts
It tries to work as emacs does, by checking if current line is already
underlined or not. If it's not, then insert a new line of '=', otherwise
cycle over underline characters.
Map the command to 'Ctrl+=' and add tests for it.
=> Add new command to underline current line.

package.json
VS Code recently started giving a warning in the configuration files for these parameters. Using the type as 'array' should solve it.
Just a pet peeve.
=> fixes "Incorrect type. Expected string[]"" warning

src/rstLsp/extension.ts
In preparation for [Visual Studio Live Share](https://aka.ms/vsls) adding support for "guests" to receive remote language services for reStructuredText, this PR simply updates the current `DocumentSelector` to be limited to `file` and `untitled` (unsaved) files. This way, when someone has the reStructuredText extension installed, and joins a Live Share session (where files use the `vsls:` scheme), their language services will be entirely derived from the remote/host side, which provides a more accurate and project-wide experience (guests in Live Share don't have local file access to the project they're collaborating with).
*Note: As an example, the TypeScript/JavaScript language services that come in-box with VS Code [already have this scheme …
=> [Discussion] [Live Share] Restricting language services to local files

src/features/utils/lintingProvider.ts
This is a followup to #86, and simply limits linting to local files. Apologies for not catching this when I sent #86, which was intended to limit all language services to local files.
// CC @lextm
=> [Live Share] Limiting linting to local files

package.json, src/extension.ts, src/features/rstDocumentContent.ts, src/features/utils/confPyFinder.ts, src/features/utils/configuration.ts, src/features/utils/statusBar.ts
=> Automatically locate Sphnix conf.py by searching the workspace and allow the user to pick if there are more than one such file

src/extension.ts
Fixes #102 
P.S. Since this now works, you might encounter people complaining about performance from `updateOnTextChanged`, since this runs `sphinx-build` on any change with a rather small timeout... and on the data on disk, not on the unsaved changes the user has made, which makes this setting kinda pointless.
=> Fix live preview

language-configuration.json, src/extension.ts
This patch provides a minimal [`LanguageConfiguration`](https://code.visualstudio.com/docs/extensionAPI/vscode-api#LanguageConfiguration) to support the comment shortcut.
=> Add toggle line comments support (Fix #115)

package-lock.json, package.json, src/features/underline.ts
Now, this plugin create too short underlines for East Asian Characters.
Expected:
```rst
あいうえお
==========
```
Actual:
```rst
あいうえお
=====
```
`docutils` compute underline width with East Asian Width which was defined by Unicode: http://unicode.org/reports/tr11/
I fixed this issue.
P.S.
Strictly speaking, `docutils` also use "combining class" of Unicode characters at https://sourceforge.net/p/docutils/code/HEAD/tree/tags/docutils-0.14/docutils/utils/__init__.py#l643
However, I cannot find good solutions to get "combining class" in JavaScript.
Because longer underline width is not problem, I removed the logic using combining class and added normalizing, `String.prototype.normalize` helps to calculate the correct length of string including combining characters in many cases.
=> Fix underline width

syntaxes/restructuredtext.tmLanguage
Thanks for providing this awesome extension :)
This PR attempts to fix issues with the syntax highlighting of inline substitutions and substitution directives. Here are before and after images of the proposed changes:
The extension currently highlights the opening `|` in the inline substitutions as punctuation, but highlights the closing `|` with the same scope as the substitution itself. I have rearranged the scopes so that only the inner text receives the underlined substitution formatting, and both pipes are formatted as punctuation. This also helps with readability, particularly when there are trailing underscores (substitutions that are also links).
The substitution directives are not currently highlighted at all, because the lexer is thrown off by the fact that the directive itself …
=> correct syntax highlighting for inline substitutions and directives

package.json, src/features/utils/configuration.ts, src/features/utils/constants.ts, src/python.ts, src/rstEngine.ts
According to the announcement made by the vscode-python extension, it is not possible to use the pythonPath setting anymore.
Therefore, it is necessary to make use of the API provided by the vscode-python extension
https://github.com/microsoft/vscode-python/issues/12596
Fix #222
This fix still needs some refinement and surely some feedback.
=> Remove dependency on the pythonPath setting

language-configuration.json
Adding the increaseIndentPattern rule will indent the content after the directives are written.
=> Add increaseIndentPattern rule to the language configuration

python-scripts/preview.py
if system encoding is not use UTF-8 (like Windows in Japanese environment using CP932), preview.py don't work.  This PR changes it using  `sys.getdefaultencoding()`.
=> use system default encoding in preview.py

package.json
I was using another extension (GitHub CoPilot) and I was finding that the tab-to-complete wasn't working with it. Similar to the diagnosis at https://github.com/yzhang-gh/vscode-markdown/issues/1011, the keybinding for this extension was taking precedence, eating the tab before CoPilot could get it. Therefore, this PR makes the keybinding more strict in when it accepts a "tab" event.
Tested on my machine, it fixes the problem as described in that issue. Not sure if this will affect other aspects of this extension?
=> Make "tab" keybinding compatible with other extensions

package.json
Small PR to fix a minor bug I encountered today when I inserted a snippet via suggestion while in a list and then attempted to switch between the snippet placeholders using `tab` and `shift+tab`.
VSCode did not switch the placeholders as expected but instead triggered the suggestions popup. After a short inspection with the keybinding troubleshooter, it became apparent that the [`resttext.key.tab`](https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/master/package.json#L211) and [`resttext.key.shift.tab`](https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/master/package.json#L216) keybindings were intercepting the keypresses because the editor was still in a list.
Looking at the handlers registered for these keybindings, when using `tab` or …
=> Disables resttext tab and shift+tab keybindings in snippet mode

src/preview/confPyFinder.ts, src/preview/rstEngine.ts, src/preview/selector.ts, src/preview/statusBar.ts, src/test/suite/preview.test.ts, src/util/configuration.ts
The esbonio language server can, in some cases, automatically discover the location of a project's `conf.py` file without requiring the `esbonio.sphinx.confDir` option to be set. 
When previewing a project that is implicitly configured like this, the vscode-restructuredtext extension should still be able to offer the Sphinx powered preview.
However, since the `RSTEngine` sources its `confPyDirectory` from the settings file rather than the esbonio client the extension incorrectly shows the docutils based preview instead.
This PR
- Reworks the `RSTEngine` to use the esbonio client to determine the directory holding the `conf.py` file, enabling the Sphinx based preview to be used with implicitly configured projects. 
Rather than checking for `confPyDirectory == ''`, a docutils based preview …
=> Fix preview when "implicit" esbonio configs are used

src/language-server/client.ts
This fixes issue #404
By setting `shell=true` in the options structure, environment variables from the calling process are passed down into the `sphinx-build` process. This includes the `PYTHONPATH` variable, which allows Sphinx to find modules that are not in the default system path.
=> Pass shell environment though to Sphinx process (Fixes issue #404)

src/linter/extension.ts
=> Fix No module named `rstcheck.__main__`

src/linter/extension.ts
resolves `RuntimeWarning: 'doc8.main' found in sys.modules after import of package 'doc8', but prior to execution of 'doc8.main'; this may result in unpredictable behaviour` by changing doc8 execution from "doc8.main" to "doc8".
The above screenshot shows this warning being reported in `PROBLEMS`.
The warning is caused by [`doc8.__init__`](https://github.com/PyCQA/doc8/blob/main/src/doc8/__init__.py) importing `doc8.main` resulting in `python -m doc8.main` causing the import to happen twice. `python -m doc8` resolves this as [`doc8.__main__`](https://github.com/PyCQA/doc8/blob/main/src/doc8/__main__.py) implements the execution of `doc8.main` when called this way.
---
Note I was unable to get `yarn run pretest && yarn run test` to run locally so relying on GitHub actions to perform tests …
=> fix doc8 `RuntimeWarning`
